import {
  EnvelopeIcon,
  EyeIcon,
  ShoppingCartIcon,
  HeartIcon,
  UserIcon,
  XMarkIcon,
  MagnifyingGlassIcon,
  PlayCircleIcon,
  ChatBubbleBottomCenterIcon,
  AdjustmentsVerticalIcon,
  MapPinIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  TruckIcon,
  ArrowPathIcon,
  PhoneIcon,
  BellIcon,
} from '@heroicons/react/24/outline';

export const Icons = {
  user: UserIcon,
  bell: BellIcon,
  x: XMarkIcon,
  shoppingCart: ShoppingCartIcon,
  heart: HeartIcon,
  envelope: EnvelopeIcon,
  eye: EyeIcon,
  search: MagnifyingGlassIcon,
  play: PlayCircleIcon,
  chat: ChatBubbleBottomCenterIcon,
  filter: AdjustmentsVerticalIcon,
  mapPin: MapPinIcon,
  arrowRight: ArrowRightIcon,
  arrowLeft: ArrowLeftIcon,
  truck: TruckIcon,
  arrowPath: ArrowPathIcon,
  phone: PhoneIcon,
};
